### ISSUE TITLE
Retroactive loading of dataset is broken

### ISSUE THREAD

**Issue by deevis** [cavvia/forgetsy#5]
For starters, the sample on the main README is broken:

    follows_delta = Forgetsy::Delta.fetch('user_follows')
    follows_delta.incr('UserFoo', date: 2.weeks.ago)
    follows_delta.incr('UserBar', date: 10.days.ago)
    follows_delta.incr('UserBar', date: 1.week.ago)
    follows_delta.incr('UserFoo', date: 1.day.ago)
    follows_delta.incr('UserFoo')

Each of the calls to follows_delta.incr results in a NOOP because Forgetsy::Set.valid_incr_date returns false in each case that date is explicitly included...

    puts follows_delta.fetch

    {"UserFoo"=>0.9997776321896626}

**Comment by cavvia** [comment]
Thanks for spotting that! The readme had omitted the `date` option from the call to the factory method used to create the Delta. If you switch to version 0.2.7 I've added a replay flag which makes this simpler, so you can create a delta like so - 

```ruby
follows_delta = Forgetsy::Delta.create('user_follows', t: 1.week, replay: true)
```

And then start adding retrospective events to it. In the case of the example above it will actually return something like

```ruby
{ 'UserFoo' => 0.667, 'UserBar' => 0.500 }
```
